batch.target.schedule=17:00
batch.offer.schedule=17:30
batch.message.schedule=18:00
batch.channel.send.schedule=19:00
batch.result.schedule=02:00
batch.performance.schedule=04:00
batch.result.offer.table=OFFER_RESULT
batch.performance.offer.source=OFFER_RESP_HIST
batch.channel.send.transaction.scope=CAMPAIGN
